export const locale = 'fr'
export const isBigLimit = 5

export const mainEntityNames = {
  institution: 'Institution',
  folder: 'Dossier',
  tag: 'Mot clé',
  doc: 'Doc',
  dataset: 'Dataset',
  variable: 'Variable',
  modality: 'Modalité',
} as const

export const entityNames = {
  ...mainEntityNames,
  owner: 'Fournisseur',
  manager: 'Gestionnaire',
  value: 'Valeur',
  freq: 'Fréquence',
  log: 'Log',
} as const

export const parentEntities = {
  institution: 'parent',
  folder: 'parent',
  tag: 'parent',
  doc: 'parent',
  dataset: 'folder',
  variable: 'dataset',
  modality: 'folder',
  value: 'modality',
  freq: 'variable',
} as const

export const varTypes = {
  integer: 'nombre',
  float: 'décimal',
  string: 'texte',
  boolean: 'booléen',
  date: 'date',
  datetime: 'date-heure',
  time: 'heure',
  geometry: 'géométrie',
  other: 'autre',
} as const

export const evolutionTypes = {
  add: 'Ajout',
  update: 'Modification',
  delete: 'Suppression',
  startDate: 'Validité début',
  endDate: 'Validité fin',
  lastUpdateDate: 'Dernière mise à jour',
  nextUpdateDate: 'Prochaine mise à jour',
} as const

export const columnCleanNames = {
  startDate: 'Validité début',
  endDate: 'Validité fin',
  lastUpdate: ['Dernière', 'mise à jour'],
  lastUpdateDate: ['Dernière', 'mise à jour'],
  nextUpdateDate: ['Prochaine', 'mise à jour'],
  name: 'Nom',
  description: 'Description',
  updatingEach: ['Fréquence', 'de mise à jour'],
  nbRow: 'Nombre de lignes',
  nbFiles: 'Nombre de fichiers',
} as const

export const columnIcons = {
  updatingEach: 'frequency',
  lastUpdate: 'lastUpdateDate',
} as const

export const entityToIcon = {
  md: 'md',
  github: 'github',
  institution: 'university',
  owner: 'university',
  manager: 'university',
  folder: 'folder',
  tag: 'tag',
  dataset: 'table',
  variable: 'grip-lines-vertical',
  modality: 'align-left',
  value: 'ellipsis-vertical',
  doc: 'book',
  about: 'info-circle',
  favorite: 'star',
  log: 'warehouse',
  search: 'magnifying-glass',
  colSearch: 'magnifying-glass',
  recentSearch: 'clock-rotate-left',
  type: 't',
  missing: 'circle-question',
  duplicate: 'clone',
  frequency: 'calendar-alt',
  date: 'calendar-day',
  dateRange: 'calendar-week',
  startDate: 'calendar-check',
  endDate: 'calendar-xmark',
  lastUpdateDate: 'rotate-right',
  nextUpdateDate: 'rotate-left',
  downloadFile: 'file-arrow-down',
  download: 'cloud-download-alt',
  upload: 'cloud-arrow-up',
  downloadClose: 'cloud-arrow-down fa-rotate-180',
  pdf: 'file-pdf',
  compare: 'object-ungroup',
  option: 'gear',
  diagram: 'diagram-project',
  email: 'envelope',
  deliveryFormat: 'laptop-file',
  surveyType: 'database',
  metadataPath: 'sitemap',
  level: 'layer-group',
  folderTree: 'folder-tree',
  folderTreeInstitution: 'folder-tree',
  folderTreeFolder: 'folder-tree',
  folderTreeTag: 'folder-tree',
  gitCode: 'code-branch',
  tab: 'folder-closed',
  page: 'file-lines',
  entity: 'globe',
  timeAgo: 'clock',
  stat: 'signal',
  localisation: 'location-dot',
  dataPath: 'server',
  name: 'signature',
  description: 'comment',
  nbRow: 'grip-lines',
  nbFiles: 'copy',
  link: 'link',
  recursive: 'rotate-left',
  functionality: 'screwdriver-wrench',
  preview: 'eye',
  relation: 'arrows-left-right',
  evolution: 'history',
  add: 'plus',
  update: 'pen',
  delete: 'trash',
  internalView: 'box-open',
  internalId: 'fingerprint',
  nbSource: 'arrow-up',
  nbDerived: 'arrow-down',
  freq: 'chart-bar',
} as const
