export const locale = 'fr'
export const isBigLimit = 5

export const mainEntityNames = {
  organization: 'Organisation',
  folder: 'Dossier',
  tag: 'Mot clé',
  concept: 'Concept',
  doc: 'Doc',
  dataset: 'Dataset',
  variable: 'Variable',
  enumeration: 'Énumération',
} as const

export const entityNames = {
  ...mainEntityNames,
  owner: 'Fournisseur',
  manager: 'Gestionnaire',
  value: 'Valeur',
  frequency: 'Fréquence',
  log: 'Log',
} as const

export const parentEntities = {
  organization: 'parent',
  folder: 'parent',
  tag: 'parent',
  concept: 'parent',
  doc: 'parent',
  dataset: 'folder',
  variable: 'dataset',
  enumeration: 'folder',
  value: 'enumeration',
  frequency: 'variable',
} as const

export const varTypes = {
  integer: 'nombre',
  float: 'décimal',
  string: 'texte',
  boolean: 'booléen',
  date: 'date',
  datetime: 'date-heure',
  time: 'heure',
  geometry: 'géométrie',
  binary: 'binaire',
  other: 'autre',
} as const

export const evolutionTypes = {
  add: 'Ajout',
  update: 'Modification',
  delete: 'Suppression',
  startDate: 'Validité début',
  endDate: 'Validité fin',
  lastUpdateDate: 'Dernière mise à jour',
  nextUpdateDate: 'Prochaine mise à jour',
} as const

export const columnCleanNames = {
  startDate: 'Validité début',
  endDate: 'Validité fin',
  lastUpdate: ['Dernière', 'mise à jour'],
  lastUpdateDate: ['Dernière', 'mise à jour'],
  nextUpdateDate: ['Prochaine', 'mise à jour'],
  name: 'Nom',
  description: 'Description',
  updatingEach: ['Fréquence', 'de mise à jour'],
  nbRow: 'Nombre de lignes',
  nbResources: 'Nombre de ressources',
  dataSize: 'Taille des données',
  min: 'Minimum',
  max: 'Maximum',
  mean: 'Moyenne',
  std: 'Écart-type',
} as const

export const columnIcons = {
  updatingEach: 'updateFrequency',
  lastUpdate: 'lastUpdateDate',
  min: 'stat',
  max: 'stat',
  mean: 'stat',
  std: 'stat',
} as const

export const entityToIcon = {
  md: 'md',
  github: 'github',
  organization: 'building-user',
  owner: 'building-user',
  manager: 'building-user',
  folder: 'folder',
  tag: 'tag',
  concept: 'lightbulb',
  dataset: 'table',
  variable: 'grip-lines-vertical',
  enumeration: 'align-left',
  value: 'ellipsis-vertical',
  doc: 'book',
  about: 'info-circle',
  openapi: 'database',
  dcat: 'bezier-curve',
  dashboard: 'clipboard-check',
  inventory: 'clipboard-list',
  coverage: 'layer-group',
  understanding: 'book-open-reader',
  discoverability: 'magnifying-glass-chart',
  governance: 'building-user',
  profileQuality: 'chart-line',
  profiling: 'chart-line',
  dataQuality: 'chart-column',
  lifecycle: 'rotate-right',
  protection: 'shield-halved',
  usability: 'laptop-file',
  freshness: 'rotate-right',
  structure: 'sitemap',
  publication: 'share-nodes',
  integrity: 'check',
  interoperability: 'network-wired',
  favorite: 'star',
  log: 'warehouse',
  search: 'magnifying-glass',
  colSearch: 'magnifying-glass',
  recentSearch: 'clock-rotate-left',
  type: 't',
  missing: 'circle-question',
  duplicate: 'clone',
  businessKey: 'id-card',
  updateFrequency: 'calendar-alt',
  date: 'calendar-day',
  dateRange: 'calendar-week',
  startDate: 'calendar-check',
  endDate: 'calendar-xmark',
  lastUpdateDate: 'rotate-right',
  nextUpdateDate: 'rotate-left',
  downloadFile: 'file-arrow-down',
  download: 'cloud-download-alt',
  upload: 'cloud-arrow-up',
  downloadClose: 'cloud-arrow-down fa-rotate-180',
  pdf: 'file-pdf',
  compare: 'object-ungroup',
  back: 'arrow-left',
  option: 'gear',
  diagram: 'diagram-project',
  email: 'envelope',
  deliveryFormat: 'laptop-file',
  license: 'scale-balanced',
  surveyType: 'database',
  metadataPath: 'sitemap',
  level: 'layer-group',
  folderTree: 'folder-tree',
  folderTreeOrganization: 'folder-tree',
  folderTreeFolder: 'folder-tree',
  folderTreeTag: 'folder-tree',
  folderTreeConcept: 'folder-tree',
  gitCode: 'code-branch',
  tab: 'folder-closed',
  page: 'file-lines',
  entity: 'globe',
  timeAgo: 'clock',
  stat: 'signal',
  localisation: 'location-dot',
  dataPath: 'server',
  name: 'signature',
  description: 'comment',
  nbRow: 'grip-lines',
  nbResources: 'copy',
  dataSize: 'weight-hanging',
  link: 'link',
  recursive: 'rotate-left',
  propagateToParents: 'arrow-up',
  features: 'screwdriver-wrench',
  preview: 'eye',
  relation: 'arrows-left-right',
  evolution: 'history',
  add: 'plus',
  update: 'pen',
  delete: 'trash',
  internalView: 'box-open',
  internalId: 'fingerprint',
  nbSource: 'arrow-up',
  nbDerived: 'arrow-down',
  fk: 'key',
  frequency: 'chart-bar',
} as const
