import type { TranslationKey } from '@i18n/types'

export const isBigLimit = 5

export const mainEntityNames = {
  organization: 'entity.organization',
  folder: 'entity.folder',
  tag: 'entity.tag',
  concept: 'entity.concept',
  doc: 'entity.doc',
  dataset: 'entity.dataset',
  variable: 'entity.variable',
  enumeration: 'entity.enumeration',
} as const satisfies { [key: string]: TranslationKey }

export const entityNames = {
  ...mainEntityNames,
  owner: 'entity.owner',
  manager: 'entity.manager',
  value: 'entity.value',
  frequency: 'entity.frequency',
  log: 'entity.log',
} as const satisfies { [key: string]: TranslationKey }

export const parentEntities = {
  organization: 'parent',
  folder: 'parent',
  tag: 'parent',
  concept: 'parent',
  doc: 'parent',
  dataset: 'folder',
  variable: 'dataset',
  enumeration: 'folder',
  value: 'enumeration',
  frequency: 'variable',
} as const

export const varTypes = {
  integer: 'varType.integer',
  float: 'varType.float',
  string: 'varType.string',
  boolean: 'varType.boolean',
  date: 'varType.date',
  datetime: 'varType.datetime',
  time: 'varType.time',
  geometry: 'varType.geometry',
  binary: 'varType.binary',
  other: 'varType.other',
} as const satisfies { [key: string]: TranslationKey }

export const evolutionTypes = {
  add: 'evolution.type.add',
  update: 'evolution.type.update',
  delete: 'evolution.type.delete',
  startDate: 'evolution.type.startDate',
  endDate: 'evolution.type.endDate',
  lastUpdateDate: 'evolution.type.lastUpdateDate',
  nextUpdateDate: 'evolution.type.nextUpdateDate',
} as const satisfies { [key: string]: TranslationKey }

export const columnCleanNames = {
  startDate: 'evolution.column.startDate',
  endDate: 'evolution.column.endDate',
  lastUpdate: [
    'evolution.column.lastUpdate.line1',
    'evolution.column.lastUpdate.line2',
  ],
  lastUpdateDate: [
    'evolution.column.lastUpdate.line1',
    'evolution.column.lastUpdate.line2',
  ],
  nextUpdateDate: [
    'evolution.column.nextUpdate.line1',
    'evolution.column.nextUpdate.line2',
  ],
  name: 'column.name.title',
  description: 'column.description.title',
  updatingEach: [
    'evolution.column.updatingEach.line1',
    'evolution.column.updatingEach.line2',
  ],
  nbRow: 'column.rows.tooltip',
  nbResources: 'column.resources.tooltip',
  dataSize: 'column.size.tooltip',
  min: 'evolution.column.min',
  max: 'evolution.column.max',
  mean: 'evolution.column.mean',
  std: 'evolution.column.std',
} as const satisfies {
  [key: string]: TranslationKey | readonly [TranslationKey, TranslationKey]
}

export const columnIcons = {
  updatingEach: 'updateFrequency',
  lastUpdate: 'lastUpdateDate',
  min: 'stat',
  max: 'stat',
  mean: 'stat',
  std: 'stat',
} as const

export const entityToIcon = {
  md: 'md',
  github: 'github',
  organization: 'building-user',
  owner: 'building-user',
  manager: 'building-user',
  folder: 'folder',
  tag: 'tag',
  concept: 'lightbulb',
  dataset: 'table',
  variable: 'grip-lines-vertical',
  enumeration: 'align-left',
  value: 'ellipsis-vertical',
  doc: 'book',
  about: 'info-circle',
  openapi: 'database',
  dcat: 'bezier-curve',
  dashboard: 'clipboard-check',
  inventory: 'clipboard-list',
  coverage: 'layer-group',
  understanding: 'book-open-reader',
  discoverability: 'magnifying-glass-chart',
  governance: 'building-user',
  profileQuality: 'chart-line',
  profiling: 'chart-line',
  dataQuality: 'chart-column',
  lifecycle: 'rotate-right',
  protection: 'shield-halved',
  usability: 'laptop-file',
  freshness: 'rotate-right',
  structure: 'sitemap',
  publication: 'share-nodes',
  integrity: 'check',
  interoperability: 'network-wired',
  favorite: 'star',
  log: 'warehouse',
  search: 'magnifying-glass',
  colSearch: 'magnifying-glass',
  recentSearch: 'clock-rotate-left',
  type: 't',
  missing: 'circle-question',
  duplicate: 'clone',
  businessKey: 'id-card',
  updateFrequency: 'calendar-alt',
  date: 'calendar-day',
  dateRange: 'calendar-week',
  startDate: 'calendar-check',
  endDate: 'calendar-xmark',
  lastUpdateDate: 'rotate-right',
  nextUpdateDate: 'rotate-left',
  downloadFile: 'file-arrow-down',
  download: 'cloud-download-alt',
  upload: 'cloud-arrow-up',
  downloadClose: 'cloud-arrow-down fa-rotate-180',
  pdf: 'file-pdf',
  compare: 'object-ungroup',
  back: 'arrow-left',
  option: 'gear',
  diagram: 'diagram-project',
  email: 'envelope',
  deliveryFormat: 'laptop-file',
  license: 'scale-balanced',
  surveyType: 'database',
  metadataPath: 'sitemap',
  level: 'layer-group',
  folderTree: 'folder-tree',
  folderTreeOrganization: 'folder-tree',
  folderTreeFolder: 'folder-tree',
  folderTreeTag: 'folder-tree',
  folderTreeConcept: 'folder-tree',
  gitCode: 'code-branch',
  tab: 'folder-closed',
  page: 'file-lines',
  entity: 'globe',
  timeAgo: 'clock',
  stat: 'signal',
  localisation: 'location-dot',
  dataPath: 'server',
  name: 'signature',
  description: 'comment',
  nbRow: 'grip-lines',
  nbResources: 'copy',
  dataSize: 'weight-hanging',
  link: 'link',
  recursive: 'rotate-left',
  propagateToParents: 'arrow-up',
  features: 'screwdriver-wrench',
  preview: 'eye',
  relation: 'arrows-left-right',
  evolution: 'history',
  add: 'plus',
  update: 'pen',
  delete: 'trash',
  internalView: 'box-open',
  internalId: 'fingerprint',
  nbSource: 'arrow-up',
  nbDerived: 'arrow-down',
  fk: 'key',
  frequency: 'chart-bar',
} as const
