// Base types (no dependencies)
export type {
  BaseEntity,
  Config,
  NullableNumber,
  Value,
  Frequency,
  Favorite,
  FilterActive,
  Option,
  SearchHistory,
  Filter,
  Row,
  Column,
} from './base'

// Entity types (business logic)
export type {
  ModalitySimilitute,
  WithRecursiveParent,
  WithTags,
  WithDocs,
  WithFavorite,
  WithPeriod,
  EntityWithRelations,
  Dataset,
  Variable,
  Modality,
  Folder,
  Organization,
  Tag,
  TagWithChildren,
  Concept,
  ConceptWithChildren,
  Doc,
  FreqPreview,
  Log,
  MetaVariable,
  MetaDataset,
  MetaFolder,
  Evolution,
  AnyEntity,
  EntityTypeMap,
  EntityName,
  ParentableEntityName,
  ParentableEntityTypeMap,
  ParentableEntity,
  ParentableEntityItem,
  FavoritableEntityName,
  FavoritableEntityMap,
  FavoritableEntity,
  TaguableEntityName,
  TaguableEntityMap,
  TaguableEntity,
  RecursiveEntityName,
  RecursiveEntityMap,
  RecursiveEntity,
  DocableEntityName,
  DocableEntityMap,
  DocableEntity,
  PeriodableEntityName,
  PeriodableEntityMap,
  PeriodableEntity,
  MainEntity,
  MainEntityName,
  MainEntityMap,
} from './entity'

// Global declarations are auto-imported
import './global'
import './module'
