# common-startup.ps1
# Unified install/uninstall for datannur Windows auto-start.
# Two independent targets: 'app' (HTTP server, no deps) and 'llm' (Python sidecar).
# User-scope only: no admin, no services, no scheduled tasks.
param(
    [Parameter(Mandatory=$true)][ValidateSet('install','uninstall')][string]$Action,
    [Parameter(Mandatory=$true)][ValidateSet('app','llm')][string]$Target,
    [Parameter(Mandatory=$true)][string]$PackageDir
)

$ErrorActionPreference = 'Stop'

# --- Paths -------------------------------------------------------------------
$startupDir        = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'
$localBootstrapDir = Join-Path $env:LOCALAPPDATA 'datannur'
$logsDir           = Join-Path $localBootstrapDir 'logs'
$appDir            = Join-Path $PackageDir 'app'
$windowsScriptsDir = Join-Path $appDir 'scripts\windows'
$pythonScriptsDir  = Join-Path $appDir 'scripts\python'
$configPath        = Join-Path $PackageDir 'data\localhost-ports.config.json'

# --- Per-target resources ----------------------------------------------------
$targets = @{
    app = @{
        LnkName       = 'datannur-app.lnk'
        BootstrapName = 'bootstrap-app.ps1'
        ServeScript   = Join-Path $windowsScriptsDir 'serve-app.ps1'
        PortKey       = 'appPort'
        DefaultPort   = 61291
        ServeArgs     = @{ NoBrowser = $true }
    }
    llm = @{
        LnkName       = 'datannur-llm.lnk'
        BootstrapName = 'bootstrap-llm.ps1'
        ServeScript   = Join-Path $windowsScriptsDir 'serve-llm.ps1'
        PortKey       = 'llmProxyPort'
        DefaultPort   = 61292
        ServeArgs     = @{}
    }
}
$t = $targets[$Target]

$lnkPath       = Join-Path $startupDir $t.LnkName
# Legacy .vbs launcher from earlier versions; removed on install/uninstall.
$legacyVbsPath = Join-Path $startupDir ([IO.Path]::ChangeExtension($t.LnkName, '.vbs'))
$bootstrapPath = Join-Path $localBootstrapDir $t.BootstrapName

# --- Helpers -----------------------------------------------------------------
function Get-ConfiguredPort {
    param([string]$Key, [int]$Default)
    if (-not (Test-Path $configPath)) { return $Default }
    try {
        $cfg = Get-Content -Raw -LiteralPath $configPath | ConvertFrom-Json
        $p = [int]$cfg.$Key
        if ($p -gt 0) { return $p }
    } catch {}
    return $Default
}

function Write-TextFileNoBom {
    param([string]$Path, [string]$Content)
    # UTF-8 without BOM: wscript.exe and PS 5.1 choke on BOM; ASCII would
    # corrupt non-ASCII paths (e.g. user names with accents).
    $enc = New-Object System.Text.UTF8Encoding($false)
    [IO.File]::WriteAllText($Path, $Content, $enc)
}

function Get-TaggedProcesses {
    param([string]$ProcName, [string]$Pattern)
    try {
        Get-CimInstance Win32_Process -Filter "Name='$ProcName'" |
            Where-Object { $_.CommandLine -and ($_.CommandLine -like "*$Pattern*") }
    } catch { @() }
}

# --- Install -----------------------------------------------------------------
function Invoke-Install {
    Write-Host "==> datannur windows setup: install [$Target]" -ForegroundColor Cyan
    Write-Host "    PackageDir: $PackageDir"

    if (-not (Test-Path $t.ServeScript)) {
        throw "Serve script not found: $($t.ServeScript)"
    }

    if ($Target -eq 'llm') {
        $proxyScript = Join-Path $pythonScriptsDir 'proxy_llm.py'
        if (-not (Test-Path $proxyScript)) {
            throw "Python script not found: $proxyScript"
        }
        try {
            $null = & python --version 2>&1
            if ($LASTEXITCODE -ne 0) { throw "python --version failed" }
        } catch {
            throw "Python is required for the 'llm' target but was not found in PATH. Install Python 3 first."
        }
    }

    New-Item -ItemType Directory -Force -Path $localBootstrapDir | Out-Null
    New-Item -ItemType Directory -Force -Path $logsDir | Out-Null

    # --- Bootstrap script (runs locally, waits for network drive) ------------
    # Serialize ServeArgs as a hashtable literal so the bootstrap can splat
    # named parameters (switches, typed values) correctly. Array splatting
    # would only pass positional args.
    if ($t.ServeArgs.Count -eq 0) {
        $serveArgsLiteral = '@{}'
    } else {
        $pairs = foreach ($k in $t.ServeArgs.Keys) {
            $v = $t.ServeArgs[$k]
            if     ($v -is [bool]) { "$k = `$$v" }
            elseif ($v -is [int])  { "$k = $v" }
            else                   { "$k = '$v'" }
        }
        $serveArgsLiteral = '@{ ' + ($pairs -join '; ') + ' }'
    }

    $bootstrapContent = @"
# Auto-generated by datannur common-startup.ps1 - do not edit manually.
# Regenerate by running install-$Target.bat from the app directory.
param([string]`$DatannurTag)  # marker on powershell.exe command line, used by uninstall to kill the right process
`$ErrorActionPreference = 'Stop'
`$target      = '$Target'
`$packageDir  = '$PackageDir'
`$serveScript = '$($t.ServeScript)'
`$serveArgs   = $serveArgsLiteral
`$logsDir     = '$logsDir'

# Rotate logs: keep last 5
try {
    if (Test-Path `$logsDir) {
        Get-ChildItem -LiteralPath `$logsDir -Filter "`$target-*.log" -File |
            Sort-Object LastWriteTime -Descending |
            Select-Object -Skip 5 |
            Remove-Item -Force -ErrorAction SilentlyContinue
    }
} catch {}

`$logFile = Join-Path `$logsDir ("`$target-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.log')
try { Start-Transcript -Path `$logFile -Append | Out-Null } catch {}

Write-Host ("[bootstrap-`$target] {0} PID=`$PID waiting for `$packageDir ..." -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))
while (-not (Test-Path `$packageDir)) { Start-Sleep -Seconds 5 }
Write-Host "[bootstrap-`$target] app dir available, launching serve script"

& `$serveScript @serveArgs
"@
    Write-TextFileNoBom -Path $bootstrapPath -Content $bootstrapContent
    Write-Host "    wrote $bootstrapPath"

    # --- Startup shortcut (.lnk) --------------------------------------------
    # A .lnk in the Startup folder is the standard persistence pattern used
    # by Teams, Slack, OneDrive, etc. Using it (instead of a .vbs wrapper)
    # avoids the VBS + hidden PowerShell combo that EDRs routinely flag.
    # -WindowStyle Hidden is kept to avoid a permanent taskbar tile per target.
    $psExe     = "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"
    $psArgs    = "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$bootstrapPath`" -DatannurTag $Target"
    $iconPath  = Join-Path $appDir 'assets\icon\icon.ico'

    # Cleanup any legacy .vbs launcher from earlier versions.
    if (Test-Path $legacyVbsPath) {
        Remove-Item -LiteralPath $legacyVbsPath -Force -ErrorAction SilentlyContinue
        Write-Host "    removed legacy $legacyVbsPath"
    }

    $WshShell = New-Object -ComObject WScript.Shell
    $shortcut = $WshShell.CreateShortcut($lnkPath)
    $shortcut.TargetPath       = $psExe
    $shortcut.Arguments        = $psArgs
    $shortcut.WorkingDirectory = $localBootstrapDir
    $shortcut.WindowStyle      = 7   # Minimized (fallback if Hidden is stripped)
    $shortcut.Description      = "datannur $Target auto-start"
    if (Test-Path $iconPath) { $shortcut.IconLocation = $iconPath }
    $shortcut.Save()
    Write-Host "    wrote $lnkPath"

    # --- Launch now ----------------------------------------------------------
    Start-Process -FilePath $lnkPath
    Start-Sleep -Seconds 3

    $port = Get-ConfiguredPort -Key $t.PortKey -Default $t.DefaultPort

    if ($Target -eq 'app') {
        Write-Host "    opening http://localhost:$port" -ForegroundColor Green
        Start-Process "http://localhost:$port"
    } else {
        $listening = $false
        try {
            $listening = [bool](Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue)
        } catch {}
        if ($listening) {
            Write-Host "    OK: llm proxy listening on port $port" -ForegroundColor Green
        } else {
            Write-Host "    WARN: llm proxy not yet listening on port $port (may still be starting)" -ForegroundColor Yellow
        }
    }

    Write-Host "==> install done. Will auto-start at next login." -ForegroundColor Cyan
}

# --- Uninstall ---------------------------------------------------------------
function Invoke-Uninstall {
    Write-Host "==> datannur windows setup: uninstall [$Target]" -ForegroundColor Cyan

    if (Test-Path $lnkPath) {
        Remove-Item -LiteralPath $lnkPath -Force
        Write-Host "    removed $lnkPath"
    } else {
        Write-Host "    (no shortcut to remove)"
    }

    if (Test-Path $legacyVbsPath) {
        Remove-Item -LiteralPath $legacyVbsPath -Force
        Write-Host "    removed legacy $legacyVbsPath"
    }

    if (Test-Path $bootstrapPath) {
        Remove-Item -LiteralPath $bootstrapPath -Force
        Write-Host "    removed $bootstrapPath"
    } else {
        Write-Host "    (no bootstrap to remove)"
    }

    # Kill tagged PowerShell processes
    $psProcs = Get-TaggedProcesses -ProcName 'powershell.exe' -Pattern "DatannurTag $Target"
    foreach ($p in $psProcs) {
        try {
            Stop-Process -Id $p.ProcessId -Force -ErrorAction Stop
            Write-Host "    killed powershell PID $($p.ProcessId)"
        } catch {
            Write-Host "    failed to kill powershell PID $($p.ProcessId): $_" -ForegroundColor Yellow
        }
    }

    if ($Target -eq 'llm') {
        # Match versioned / aliased / windowed variants: python.exe, pythonw.exe,
        # python3.12.exe, Microsoft Store python.exe, etc.
        $pyProcs = try {
            Get-CimInstance Win32_Process -Filter "Name LIKE 'python%.exe'" |
                Where-Object { $_.CommandLine -and ($_.CommandLine -like '*proxy_llm*') }
        } catch { @() }
        foreach ($p in $pyProcs) {
            try {
                Stop-Process -Id $p.ProcessId -Force -ErrorAction Stop
                Write-Host "    killed python PID $($p.ProcessId)"
            } catch {
                Write-Host "    failed to kill python PID $($p.ProcessId): $_" -ForegroundColor Yellow
            }
        }
    }

    Write-Host "==> uninstall done." -ForegroundColor Cyan
}

# --- Dispatch ----------------------------------------------------------------
try {
    if ($Action -eq 'install') { Invoke-Install } else { Invoke-Uninstall }
} catch {
    Write-Host "ERROR: $_" -ForegroundColor Red
    exit 1
}
